# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import finance_kids_pb2 as finance__kids__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in finance_kids_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FinanceKidsServiceStub(object):
    """─────────────────────────────────────────────────────────────────
    Servicio gRPC — Finance Kids (Plataforma educativa de finanzas)
    Permite gestionar lecciones, quizzes y progreso de los niños
    ─────────────────────────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLesson = channel.unary_unary(
                '/financekids.FinanceKidsService/GetLesson',
                request_serializer=finance__kids__pb2.LessonRequest.SerializeToString,
                response_deserializer=finance__kids__pb2.LessonResponse.FromString,
                _registered_method=True)
        self.ListLessons = channel.unary_unary(
                '/financekids.FinanceKidsService/ListLessons',
                request_serializer=finance__kids__pb2.EmptyRequest.SerializeToString,
                response_deserializer=finance__kids__pb2.LessonListResponse.FromString,
                _registered_method=True)
        self.SubmitQuizAnswer = channel.unary_unary(
                '/financekids.FinanceKidsService/SubmitQuizAnswer',
                request_serializer=finance__kids__pb2.QuizAnswerRequest.SerializeToString,
                response_deserializer=finance__kids__pb2.QuizAnswerResponse.FromString,
                _registered_method=True)
        self.GetProgress = channel.unary_unary(
                '/financekids.FinanceKidsService/GetProgress',
                request_serializer=finance__kids__pb2.ProgressRequest.SerializeToString,
                response_deserializer=finance__kids__pb2.ProgressResponse.FromString,
                _registered_method=True)
        self.GetBadges = channel.unary_unary(
                '/financekids.FinanceKidsService/GetBadges',
                request_serializer=finance__kids__pb2.BadgeRequest.SerializeToString,
                response_deserializer=finance__kids__pb2.BadgeResponse.FromString,
                _registered_method=True)


class FinanceKidsServiceServicer(object):
    """─────────────────────────────────────────────────────────────────
    Servicio gRPC — Finance Kids (Plataforma educativa de finanzas)
    Permite gestionar lecciones, quizzes y progreso de los niños
    ─────────────────────────────────────────────────────────────────
    """

    def GetLesson(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListLessons(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitQuizAnswer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBadges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FinanceKidsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLesson': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLesson,
                    request_deserializer=finance__kids__pb2.LessonRequest.FromString,
                    response_serializer=finance__kids__pb2.LessonResponse.SerializeToString,
            ),
            'ListLessons': grpc.unary_unary_rpc_method_handler(
                    servicer.ListLessons,
                    request_deserializer=finance__kids__pb2.EmptyRequest.FromString,
                    response_serializer=finance__kids__pb2.LessonListResponse.SerializeToString,
            ),
            'SubmitQuizAnswer': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitQuizAnswer,
                    request_deserializer=finance__kids__pb2.QuizAnswerRequest.FromString,
                    response_serializer=finance__kids__pb2.QuizAnswerResponse.SerializeToString,
            ),
            'GetProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProgress,
                    request_deserializer=finance__kids__pb2.ProgressRequest.FromString,
                    response_serializer=finance__kids__pb2.ProgressResponse.SerializeToString,
            ),
            'GetBadges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBadges,
                    request_deserializer=finance__kids__pb2.BadgeRequest.FromString,
                    response_serializer=finance__kids__pb2.BadgeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'financekids.FinanceKidsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('financekids.FinanceKidsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FinanceKidsService(object):
    """─────────────────────────────────────────────────────────────────
    Servicio gRPC — Finance Kids (Plataforma educativa de finanzas)
    Permite gestionar lecciones, quizzes y progreso de los niños
    ─────────────────────────────────────────────────────────────────
    """

    @staticmethod
    def GetLesson(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/financekids.FinanceKidsService/GetLesson',
            finance__kids__pb2.LessonRequest.SerializeToString,
            finance__kids__pb2.LessonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListLessons(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/financekids.FinanceKidsService/ListLessons',
            finance__kids__pb2.EmptyRequest.SerializeToString,
            finance__kids__pb2.LessonListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitQuizAnswer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/financekids.FinanceKidsService/SubmitQuizAnswer',
            finance__kids__pb2.QuizAnswerRequest.SerializeToString,
            finance__kids__pb2.QuizAnswerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/financekids.FinanceKidsService/GetProgress',
            finance__kids__pb2.ProgressRequest.SerializeToString,
            finance__kids__pb2.ProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBadges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/financekids.FinanceKidsService/GetBadges',
            finance__kids__pb2.BadgeRequest.SerializeToString,
            finance__kids__pb2.BadgeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
